version: 1.2.0
type: workflow-registry
name: artifact-driven-dev-team

description: >
  Artifact-driven virtual software development team workflow.
  Stage transitions are strictly driven by StageSummary artifacts.
  Each stage has exactly one completion anchor.

# =========================
# 1. Stagesï¼ˆé˜¶æ®µå®šä¹‰ + å”¯ä¸€å®Œæˆé”šç‚¹ï¼‰
# =========================
stages:
  - name: Planning
    order: 1
    owner: PM
    completion_condition:
      - PlanningStageSummary.completed

  - name: Design
    order: 2
    owner: Architect
    completion_condition:
      - DesignStageSummary.completed

  - name: Implementation
    order: 3
    owner: BackendEngineer
    completion_condition:
      - ImplementationStageSummary.completed

  - name: QA
    order: 4
    owner: QA
    completion_condition:
      - TestReport.approved

# =========================
# 2. Agentsï¼ˆå‚ä¸Žè§’è‰²ï¼‰
# =========================
agents:
  - name: PM
    stage: Planning
    enabled: true

  - name: PJM
    stage: Planning
    enabled: true

  - name: UXDesigner
    stage: Design
    enabled: true

  - name: UIDesigner
    stage: Design
    enabled: true

  - name: Architect
    stage: Design
    enabled: true

  - name: BackendEngineer
    stage: Implementation
    enabled: true

  - name: FrontendEngineer
    stage: Implementation
    enabled: true

  - name: QA
    stage: QA
    enabled: true

# =========================
# 3. Triggersï¼ˆArtifact é©±åŠ¨æ‰§è¡Œï¼‰
# =========================
triggers:

  # ---- Planning ----
  - agent: PM
    when:
      artifact_created: RawIdea
    hooks:
      - before_prd_create

  - agent: PJM
    when:
      artifact_approved: PRD

  - agent: PM
    when:
      artifact_approved: Backlog
    hooks:
      - finalize_planning_stage

  - agent: BackendEngineer
    when:
      artifact_completed: BackendImplementation
    produce:
      - AgentProgressReport

  - agent: FrontendEngineer
    when:
      artifact_completed: FrontendImplementation
    produce:
      - AgentProgressReport

  # ---- Design ----
  - agent: UXDesigner
    when:
      artifact_approved: PRD

  - agent: UIDesigner
    when:
      artifact_approved: UserFlow

  - agent: Architect
    when:
      all:
        - artifact_approved: PRD
        - artifact_approved: UserFlow

  - agent: Architect
    when:
      all:
        - artifact_approved: UIDesignSpec
        - artifact_approved: APISpec
    hooks:
      - finalize_design_stage

  # ---- Implementation ----
  - agent: BackendEngineer
    when:
      artifact_approved: APISpec

  - agent: FrontendEngineer
    when:
      all:
        - artifact_approved: APISpec
        - artifact_approved: UIDesignSpec

  - agent: BackendEngineer
    when:
      all:
        - artifact_completed: BackendImplementation
        - artifact_completed: FrontendImplementation
    hooks:
      - finalize_implementation_stage

  # ---- QA ----
  - agent: QA
    when:
      artifact_completed: ImplementationStageSummary

  # ---- Change Request ----
  - agent: PM
    when:
      artifact_created: ChangeRequest
    hooks:
      - evaluate_change_request

# =========================
# 4. Stage Transitionï¼ˆä¸¥æ ¼ç”± StageSummary æŽ¨è¿›ï¼‰
# =========================
stage_transition:
  - from: Planning
    to: Design
    when:
      artifact_completed: PlanningStageSummary

  - from: Design
    to: Implementation
    when:
      artifact_completed: DesignStageSummary

  - from: Implementation
    to: QA
    when:
      artifact_completed: ImplementationStageSummary

# =========================
# 5. Parallelismï¼ˆå¹¶è¡Œä¸Žå°é”ï¼‰
# =========================
parallelism:
  allowed:
    - UXDesigner
    - UIDesigner
    - Architect

  blocked:
    - QA

# =========================
# 6. Failure & Rollback Policy
# =========================
failure_policy:
  on_artifact_rejected:
    action: rollback_stage
    rollback_to_stage_owner: true

  on_bug_reported:
    action: reopen_stage
    target_stage: Implementation

# =========================
# 7. Skill Keepalive
# =========================
keepalive:
  mode: artifact-driven
  refresh_on:
    - artifact_created
    - artifact_approved
    - artifact_completed
  heartbeat_log: true

# =========================
# 8. Hooksï¼ˆé˜¶æ®µå°è´¦ Hookï¼‰
# =========================
hooks:

  before_prd_create:
    description: >
      Create project folder and register project_path
      before PRD generation.
    action: |
      import os, pathlib, re

      workspace = os.path.expanduser(
        os.environ.get("OPENCLAW_WORKSPACE", "~/openclaw_workspace")
      )

      raw = input_artifacts.get("RawIdea", {})
      project_name = raw.get("title", "default_project")
      safe = re.sub(r'[^a-zA-Z0-9_]', '_', project_name)

      base = f"project-{safe}"
      path = os.path.join(workspace, base)
      i = 1
      final = path
      while os.path.exists(final):
          i += 1
          final = f"{path}-{i}"

      pathlib.Path(final).mkdir(parents=True, exist_ok=True)

      context["project_path"] = final
      context["project_name"] = safe

      with open(os.path.join(final, "README.md"), "w", encoding="utf-8") as f:
          f.write(f"# {safe}\n\n")
          f.write("PRD: project_prd.md\n")

      print(f"ðŸ“ Project initialized at {final}")

  finalize_planning_stage:
    description: >
      Create PlanningStageSummary as the single completion anchor.
    action: |
      create_artifact(
        name="PlanningStageSummary",
        status="completed"
      )
      print("âœ… Planning stage completed")

  finalize_design_stage:
    description: >
      Create DesignStageSummary as the single completion anchor.
    action: |
      create_artifact(
        name="DesignStageSummary",
        status="completed"
      )
      print("âœ… Design stage completed")

  finalize_implementation_stage:
    description: >
      Aggregate AgentProgressReport and create
      ImplementationStageSummary with readiness snapshot.
    action: |
      reports = list_artifacts(type="AgentProgressReport")

      completed_roles = []
      produced_artifacts = []
      blockers = []

      for r in reports:
          role = r.get("role")
          if role:
              completed_roles.append(role)

          produced_artifacts.extend(
              r.get("produced_artifacts", [])
          )

          if r.get("blockers"):
              blockers.extend(r["blockers"])

      qa_ready = len(blockers) == 0

      create_artifact(
        name="ImplementationStageSummary",
        status="completed",
        content={
          "completed_roles": sorted(set(completed_roles)),
          "produced_artifacts": sorted(set(produced_artifacts)),
          "blockers": blockers,
          "qa_ready": qa_ready
        }
      )

      print("âœ… Implementation stage completed")
      print(f"ðŸ“¦ Roles completed: {completed_roles}")
      print(f"ðŸ“„ Artifacts produced: {produced_artifacts}")
      print(f"ðŸš§ Blockers: {blockers}")
      print(f"ðŸ§ª QA ready: {qa_ready}")

  evaluate_change_request:
    description: >
      Evaluate ChangeRequest and decide PRD versioning strategy.
    action: |
      print("ðŸ”„ ChangeRequest evaluation triggered")
