version: 1.2.0
type: workflow-registry
name: artifact-driven-dev-team

description: >
  Artifact-driven virtual software development team workflow.
  Defines deterministic stage ownership, artifact responsibility,
  and controlled rollback / change propagation.

# =========================
# 1. Stages（阶段 + 责任边界）
# =========================
stages:

  - name: Planning
    order: 1
    owner: PM
    produces:
      - PRD
      - Backlog
    completion_condition:
      - PRD.approved
      - Backlog.approved

  - name: Design
    order: 2
    owner: Architect
    produces:
      - UserFlow
      - UIDesignSpec
      - APISpec
      - DBSchema
    completion_condition:
      - UserFlow.approved
      - UIDesignSpec.approved
      - APISpec.approved

  - name: Implementation
    order: 3
    owner: BackendEngineer
    produces:
      - BackendImplementation
      - FrontendImplementation
    completion_condition:
      - BackendImplementation.completed
      - FrontendImplementation.completed

  - name: QA
    order: 4
    owner: QA
    produces:
      - TestReport
      - BugReport
    completion_condition:
      - TestReport.approved

# =========================
# 2. Agents（角色绑定阶段）
# =========================
agents:
  - name: PM
    stage: Planning
    enabled: true

  - name: PJM
    stage: Planning
    enabled: true

  - name: UXDesigner
    stage: Design
    enabled: true

  - name: UIDesigner
    stage: Design
    enabled: true

  - name: Architect
    stage: Design
    enabled: true

  - name: BackendEngineer
    stage: Implementation
    enabled: true

  - name: FrontendEngineer
    stage: Implementation
    enabled: true

  - name: QA
    stage: QA
    enabled: true

# =========================
# 3. Triggers（唯一主驱动）
# =========================
triggers:

  # ---- Planning ----
  - agent: PM
    when:
      artifact_created: RawIdea
    hooks:
      - before_prd_create

  - agent: PJM
    when:
      artifact_approved: PRD

  # ---- Design ----
  - agent: UXDesigner
    when:
      artifact_approved: PRD

  - agent: UIDesigner
    when:
      artifact_approved: UserFlow

  - agent: Architect
    when:
      all:
        - artifact_approved: PRD
        - artifact_approved: UserFlow

  # ---- Implementation ----
  - agent: BackendEngineer
    when:
      artifact_approved: APISpec

  - agent: FrontendEngineer
    when:
      all:
        - artifact_approved: APISpec
        - artifact_approved: UIDesignSpec

  # ---- QA ----
  - agent: QA
    when:
      stage_completed: Implementation

  # ---- Change Request ----
  - agent: PM
    when:
      artifact_created: ChangeRequest
    effect:
      interrupt_stage: Planning
    hooks:
      - evaluate_change_request

# =========================
# 4. Stage Transition（严格推进）
# =========================
stage_transition:
  - from: Planning
    to: Design
    when: stage_completed

  - from: Design
    to: Implementation
    when: stage_completed

  - from: Implementation
    to: QA
    when: stage_completed

# =========================
# 5. Parallelism（安全并行）
# =========================
parallelism:
  allowed:
    - UXDesigner
    - Architect
  blocked:
    - QA

# =========================
# 6. Failure & Rollback Policy（状态机）
# =========================
failure_policy:

  on_artifact_rejected:
    action: rollback_stage
    rollback:
      to_stage: artifact.producer_stage
      artifact_state: draft

  on_bug_reported:
    action: reopen_stage
    reopen:
      stage: Implementation
      invalidate:
        - BackendImplementation
        - FrontendImplementation

# =========================
# 7. Keepalive（防模型退化）
# =========================
keepalive:
  mode: artifact-driven
  refresh_on:
    - artifact_created
    - artifact_approved
    - artifact_completed
  heartbeat_log: true

# =========================
# 8. Hooks（仅声明，不实现）
# =========================
hooks:

  before_prd_create:
    scope: workflow
    description: >
      Initialize project context before PRD generation.

  evaluate_change_request:
    scope: workflow
    description: >
      Evaluate ChangeRequest and determine PRD versioning strategy.
